### ISSUE TITLE
Ballpark rate limit? (Question only)

### ISSUE THREAD

**Issue by philosophicles** [gentlespoon/USCIS-Case-BatchQuery#3]
Hi @gentlespoon , thanks for this project. 

I'm in a similar position re EAD and have an idea for a project on similar lines, but caching results somewhere (maybe AWS DynamoDB), with a headless process updating the cache slowly on a rolling basis - rather than doing a full scrape on demand, which I think this codebase does. 

One important factor would be how sensitive the main USCIS webpage/endpoint is - at what point does it start to block requests / ban IPs? 

Since you've clearly played around with it quite a bit, do you have a sense of how many requests per second/minute/whatever one can get away with comfortably?

**Comment by gentlespoon** [comment]
Updating on a rolling basis is indeed a better idea.

I do not know the exact rate limit they placed on their webpage/endpoint. They simply put a vague message of "unusually high rate of use" without details.

I can surely share some info with you based on what I have experienced so far. It appears that they have a per minute rate limit as well as a per day rate limit. At the very beginning, I got my first IP ban after sending 2,000 requests in 5 minutes. Got banned for 24 hours. Then I lowered the rate to about 100 requests per minute, and I was able to send more than 90k requests in 15 hours until I got another ban. After that, I opted for using proxy servers to balance the load, and I haven't got a ban since then.

I hope this helps.

**Comment by gentlespoon** [comment]
Their error message did mention that you can "create a Customer account (single applicant) or a Representative account (representing many individuals)" to avoid the issue, but honestly, I do not think it is a good idea to have any personally identifiable information associated with these activities.

**Comment by philosophicles** [comment]
Thank you, that is very helpful. Would you like me to submit a simple PR that adds this information into your README? If you're happy including it there; but I understand if not.

**Comment by gentlespoon** [comment]
Sure. I would really appreciate that.
